/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_kuun_jnfs_NativeNfsContext */

#ifndef _Included_io_kuun_jnfs_NativeNfsContext
#define _Included_io_kuun_jnfs_NativeNfsContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_kuun_jnfs_NativeNfsContext_init
  (JNIEnv *, jclass);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setTcpSynCnt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setTcpSynCnt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setUid
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setUid
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setGid
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setGid
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setPageCache
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setPageCache
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setPageCacheTtl
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setPageCacheTtl
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setReadAhead
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setReadAhead
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setDebug
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setDebug
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setDirCache
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setDirCache
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setAutoReconnect
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setAutoReconnect
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setVersion
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setVersion
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setTimeout
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setTimeout
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    setClientName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_setClientName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    mount
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_mount
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    umount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_umount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    stat
 * Signature: (JLjava/lang/String;Lio/kuun/jnfs/NfsFileStat;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_stat
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    fstat
 * Signature: (JJLio/kuun/jnfs/NfsFileStat;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_fstat
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    open
 * Signature: (JLjava/lang/String;ILio/kuun/jnfs/NfsFile;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_open
  (JNIEnv *, jclass, jlong, jstring, jint, jobject);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    open2
 * Signature: (JLjava/lang/String;IILio/kuun/jnfs/NfsFile;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_open2
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jobject);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    close
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_close
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    pread
 * Signature: (JJJJ[B)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_pread
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    read
 * Signature: (JJJ[B)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_read
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    pwrite
 * Signature: (JJJJ[B)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_pwrite
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    write
 * Signature: (JJJ[B)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_write
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    lseek
 * Signature: (JJJI)J
 */
JNIEXPORT jlong JNICALL Java_io_kuun_jnfs_NativeNfsContext_lseek
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    fsync
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_fsync
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    truncate
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_truncate
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    ftruncate
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_ftruncate
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    mkdir
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_mkdir
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    mkdir2
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_mkdir2
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    rmdir
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_rmdir
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    creat
 * Signature: (JLjava/lang/String;ILio/kuun/jnfs/NfsFile;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_creat
  (JNIEnv *, jclass, jlong, jstring, jint, jobject);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    create
 * Signature: (JLjava/lang/String;IILio/kuun/jnfs/NfsFile;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_create
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jobject);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    unlink
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_unlink
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    openDir
 * Signature: (JLjava/lang/String;Lio/kuun/jnfs/NfsDir;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_openDir
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    readDir
 * Signature: (JJ)Lio/kuun/jnfs/NfsDirEnt;
 */
JNIEXPORT jobject JNICALL Java_io_kuun_jnfs_NativeNfsContext_readDir
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    seekDir
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_seekDir
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    tellDir
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_kuun_jnfs_NativeNfsContext_tellDir
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    rewindDir
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_kuun_jnfs_NativeNfsContext_rewindDir
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    closeDir
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_closeDir
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    chdir
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_chdir
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    getcwd
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_kuun_jnfs_NativeNfsContext_getcwd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    chmod
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_chmod
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    fchmod
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_fchmod
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    chown
 * Signature: (JLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_chown
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    fchown
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_fchown
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    utime
 * Signature: (JLjava/lang/String;JJ)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_utime
  (JNIEnv *, jclass, jlong, jstring, jlong, jlong);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    rename
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_kuun_jnfs_NativeNfsContext_rename
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     io_kuun_jnfs_NativeNfsContext
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_kuun_jnfs_NativeNfsContext_strerror
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
